// Starter vocabulary pack — ~200 college / SAT-tier words.
// Definitions are written in plain language (not copied from any source).
// Players can add their own words from the Word Smart book via the in-game editor.
const STARTER_WORDS = [
  { word: "aberration",   def: "something different from the usual or normal" },
  { word: "abscond",      def: "to run away suddenly, often in secret" },
  { word: "abstemious",   def: "moderate, especially with food and drink" },
  { word: "abstruse",     def: "hard to understand" },
  { word: "accolade",     def: "an award or strong expression of praise" },
  { word: "acerbic",      def: "sharp or biting, especially in tone" },
  { word: "acquiesce",    def: "to agree without protest" },
  { word: "acrimony",     def: "bitterness or harshness in words or feelings" },
  { word: "acumen",       def: "the ability to make quick, smart judgments" },
  { word: "admonish",     def: "to warn or scold gently" },
  { word: "aesthetic",    def: "relating to beauty or how something looks" },
  { word: "affable",      def: "friendly and easy to talk to" },
  { word: "aggrandize",   def: "to make something seem greater than it is" },
  { word: "alacrity",     def: "cheerful eagerness or quickness" },
  { word: "ambiguous",    def: "having more than one possible meaning" },
  { word: "ambivalent",   def: "having mixed feelings about something" },
  { word: "ameliorate",   def: "to make a bad situation better" },
  { word: "amicable",     def: "friendly and without conflict" },
  { word: "anachronism",  def: "something out of its proper time period" },
  { word: "analogous",    def: "similar in some way that allows comparison" },
  { word: "anomaly",      def: "something that doesn't fit the pattern" },
  { word: "antagonize",   def: "to make someone hostile toward you" },
  { word: "antipathy",    def: "a strong feeling of dislike" },
  { word: "apathy",       def: "a lack of interest or feeling" },
  { word: "apocryphal",   def: "of doubtful authenticity, though widely told" },
  { word: "approbation",  def: "official approval or praise" },
  { word: "arbitrary",    def: "based on personal whim, not reason" },
  { word: "arcane",       def: "secret, known only to a few" },
  { word: "archaic",      def: "very old or old-fashioned" },
  { word: "ardent",       def: "full of strong feeling or passion" },
  { word: "arduous",      def: "requiring great effort; very difficult" },
  { word: "ascetic",      def: "someone who lives with strict self-denial" },
  { word: "assiduous",    def: "showing great care and persistence" },
  { word: "assuage",      def: "to make an unpleasant feeling less intense" },
  { word: "astute",       def: "clever and quick to understand" },
  { word: "audacious",    def: "boldly daring, sometimes recklessly so" },
  { word: "augment",      def: "to make something larger or stronger" },
  { word: "auspicious",   def: "showing signs of future success" },
  { word: "austere",      def: "strict, plain, or severe" },
  { word: "avarice",      def: "extreme greed for wealth" },
  { word: "aversion",     def: "a strong dislike or wish to avoid" },
  { word: "banal",        def: "boringly common or unoriginal" },
  { word: "belie",        def: "to give a false impression of" },
  { word: "belligerent",  def: "eager to fight or argue" },
  { word: "benevolent",   def: "kind and wanting to do good" },
  { word: "benign",       def: "gentle and harmless" },
  { word: "bequeath",     def: "to leave something to someone in a will" },
  { word: "blatant",      def: "completely obvious, in a bad way" },
  { word: "bolster",      def: "to support or strengthen" },
  { word: "bombastic",    def: "using grand language to sound important" },
  { word: "brevity",      def: "shortness, especially of speech or writing" },
  { word: "burgeon",      def: "to grow or expand rapidly" },
  { word: "cacophony",    def: "a harsh mixture of loud sounds" },
  { word: "cajole",       def: "to coax with flattery or gentle pressure" },
  { word: "callous",      def: "showing no concern for others' feelings" },
  { word: "candor",       def: "honesty and openness in speech" },
  { word: "capricious",   def: "changing one's mind suddenly and often" },
  { word: "castigate",    def: "to scold or criticize harshly" },
  { word: "caustic",      def: "sharply sarcastic; able to burn or eat away" },
  { word: "censure",      def: "to express strong disapproval, often formally" },
  { word: "chagrin",      def: "a feeling of embarrassment or annoyance" },
  { word: "charlatan",    def: "a person falsely claiming special knowledge" },
  { word: "chastise",     def: "to punish or scold severely" },
  { word: "chicanery",    def: "the use of clever tricks to deceive" },
  { word: "circuitous",   def: "longer than the most direct way" },
  { word: "circumspect",  def: "careful to consider all the consequences" },
  { word: "clandestine",  def: "kept secret, often for an improper reason" },
  { word: "coalesce",     def: "to come together and form one whole" },
  { word: "cogent",       def: "clear, logical, and convincing" },
  { word: "complacent",   def: "too pleased with yourself to try harder" },
  { word: "concur",       def: "to agree with someone" },
  { word: "condone",      def: "to accept or allow behavior that is wrong" },
  { word: "conflagration",def: "an extensive and destructive fire" },
  { word: "congenial",    def: "pleasant and agreeable to be around" },
  { word: "conjecture",   def: "a guess based on incomplete information" },
  { word: "consensus",    def: "general agreement among a group" },
  { word: "contentious",  def: "likely to cause an argument" },
  { word: "contrite",     def: "feeling deeply sorry for what you did" },
  { word: "conundrum",    def: "a confusing or difficult problem" },
  { word: "copious",      def: "very large in amount" },
  { word: "corroborate",  def: "to confirm or support with evidence" },
  { word: "credulous",    def: "too ready to believe things" },
  { word: "cryptic",      def: "mysterious and hard to understand" },
  { word: "cursory",      def: "quick and not thorough" },
  { word: "dearth",       def: "a scarcity or lack of something" },
  { word: "debacle",      def: "a sudden and humiliating failure" },
  { word: "decorum",      def: "behavior that is polite and proper" },
  { word: "deference",    def: "respectful yielding to another's wishes" },
  { word: "deleterious",  def: "harmful, often in a subtle way" },
  { word: "demure",       def: "reserved, modest, and shy" },
  { word: "denigrate",    def: "to criticize unfairly; to put down" },
  { word: "deride",       def: "to make fun of in a cruel way" },
  { word: "desiccate",    def: "to dry out completely" },
  { word: "despot",       def: "a ruler with absolute and harsh power" },
  { word: "diatribe",     def: "a long, angry, critical speech" },
  { word: "didactic",     def: "intended to teach, sometimes too much so" },
  { word: "diffident",    def: "shy and lacking self-confidence" },
  { word: "digress",      def: "to wander off the main topic" },
  { word: "dilatory",     def: "slow to act, causing delay" },
  { word: "discordant",   def: "harsh and not in harmony" },
  { word: "disparage",    def: "to speak of as not worth much" },
  { word: "disparate",    def: "very different and hard to compare" },
  { word: "dissemble",    def: "to hide your true feelings or motives" },
  { word: "dogmatic",     def: "stating opinions as if they were facts" },
  { word: "dubious",      def: "doubtful; questionable" },
  { word: "duplicity",    def: "deceitful double-dealing" },
  { word: "ebullient",    def: "cheerful and full of energy" },
  { word: "eclectic",     def: "drawing from a wide variety of sources" },
  { word: "edify",        def: "to teach in a way that improves character" },
  { word: "efficacy",     def: "the power to produce a desired result" },
  { word: "effusive",     def: "showing feeling in an unrestrained way" },
  { word: "egregious",    def: "outstandingly bad; shocking" },
  { word: "elated",       def: "extremely happy and excited" },
  { word: "elicit",       def: "to draw out a response or reaction" },
  { word: "eloquent",     def: "fluent and persuasive in speaking" },
  { word: "elucidate",    def: "to make something clear; to explain" },
  { word: "emaciated",    def: "extremely thin from hunger or illness" },
  { word: "embellish",    def: "to add decorative or invented detail" },
  { word: "empirical",    def: "based on observation, not theory" },
  { word: "emulate",      def: "to imitate in order to equal or surpass" },
  { word: "enervate",     def: "to drain of energy or vitality" },
  { word: "enigmatic",    def: "difficult to interpret; mysterious" },
  { word: "ephemeral",    def: "lasting only a very short time" },
  { word: "equanimity",   def: "calmness, especially under stress" },
  { word: "equivocal",    def: "vague and open to more than one meaning" },
  { word: "erudite",      def: "showing great knowledge from study" },
  { word: "eschew",       def: "to deliberately avoid" },
  { word: "esoteric",     def: "understood by only a small group" },
  { word: "ethereal",     def: "delicate and light, almost otherworldly" },
  { word: "euphemism",    def: "a mild word used in place of a harsh one" },
  { word: "exacerbate",   def: "to make a bad situation worse" },
  { word: "exemplary",    def: "serving as an excellent example" },
  { word: "exonerate",    def: "to clear from blame or guilt" },
  { word: "expedient",    def: "useful for a quick result, even if not ideal" },
  { word: "extol",        def: "to praise enthusiastically" },
  { word: "extraneous",   def: "not relevant; unnecessary" },
  { word: "facetious",    def: "joking, often when seriousness is expected" },
  { word: "fallacious",   def: "based on a mistaken belief" },
  { word: "fastidious",   def: "very attentive to detail; hard to please" },
  { word: "fatuous",      def: "silly and pointless" },
  { word: "fervent",      def: "showing intense passion or sincerity" },
  { word: "flagrant",     def: "openly and obviously offensive" },
  { word: "florid",       def: "overly fancy or elaborate" },
  { word: "fortuitous",   def: "happening by lucky chance" },
  { word: "frugal",       def: "careful with money and resources" },
  { word: "furtive",      def: "secret and sneaky" },
  { word: "garrulous",    def: "talking too much, especially about small things" },
  { word: "germane",      def: "relevant to the topic at hand" },
  { word: "glib",         def: "speaking smoothly but insincerely" },
  { word: "grandiose",    def: "impressive in a self-important way" },
  { word: "gratuitous",   def: "uncalled for; without good reason" },
  { word: "gregarious",   def: "enjoying the company of others" },
  { word: "harangue",     def: "a long, scolding speech" },
  { word: "hackneyed",    def: "overused and no longer interesting" },
  { word: "haughty",      def: "arrogantly proud" },
  { word: "hegemony",     def: "leadership or dominance over others" },
  { word: "heretic",      def: "someone who holds a forbidden belief" },
  { word: "hubris",       def: "excessive pride that leads to a fall" },
  { word: "iconoclast",   def: "someone who attacks cherished beliefs" },
  { word: "idiosyncrasy", def: "a peculiar habit unique to a person" },
  { word: "imminent",     def: "about to happen at any moment" },
  { word: "impecunious",  def: "having very little money" },
  { word: "imperious",    def: "demanding obedience in a haughty way" },
  { word: "impetuous",    def: "acting suddenly without thinking" },
  { word: "implacable",   def: "impossible to calm or please" },
  { word: "impugn",       def: "to challenge as false or dishonest" },
  { word: "inane",        def: "silly and lacking meaning" },
  { word: "incessant",    def: "never stopping; continual" },
  { word: "inchoate",     def: "just beginning; not yet fully formed" },
  { word: "incisive",     def: "sharp and clear in thought" },
  { word: "incongruous",  def: "out of place; not fitting in" },
  { word: "indolent",     def: "lazy and avoiding effort" },
  { word: "ineffable",    def: "too great or extreme to be expressed" },
  { word: "inept",        def: "having no skill at something" },
  { word: "inexorable",   def: "impossible to stop or change" },
  { word: "ingenuous",    def: "innocent, trusting, and unsophisticated" },
  { word: "inimical",     def: "harmful or hostile" },
  { word: "innocuous",    def: "harmless and unlikely to offend" },
  { word: "insidious",    def: "harmful in a slow, hidden way" },
  { word: "insipid",      def: "lacking flavor, interest, or vigor" },
  { word: "intransigent", def: "refusing to change one's position" },
  { word: "inundate",     def: "to flood; to overwhelm with too much" },
  { word: "inveterate",   def: "long-established and unlikely to change" },
  { word: "irascible",    def: "easily angered" },
  { word: "itinerant",    def: "traveling from place to place for work" },
  { word: "jocular",      def: "fond of joking and good humor" },
  { word: "juxtapose",    def: "to place side by side for comparison" },
  { word: "kinetic",      def: "relating to motion or energy of motion" },
  { word: "laconic",      def: "using very few words" },
  { word: "languid",      def: "slow and lacking energy" },
  { word: "largesse",     def: "generosity, especially by the wealthy" },
  { word: "latent",       def: "hidden but able to develop" },
  { word: "laudable",     def: "deserving praise" },
  { word: "lethargic",    def: "sluggish and lacking energy" },
  { word: "levity",       def: "humor or lightness, often where unwelcome" },
  { word: "loquacious",   def: "very talkative" },
  { word: "lucid",        def: "easy to understand; clear-minded" },
  { word: "lugubrious",   def: "looking or sounding sad in a comical way" },
  { word: "magnanimous",  def: "generous, especially toward rivals" },
  { word: "malevolent",   def: "wishing harm on others" },
  { word: "malign",       def: "to speak badly of someone unfairly" },
  { word: "malleable",    def: "easily shaped or influenced" },
  { word: "maverick",     def: "an independent thinker who breaks rules" },
  { word: "mendacious",   def: "habitually lying" },
  { word: "mercurial",    def: "changing mood quickly and unpredictably" },
  { word: "meticulous",   def: "extremely careful about small details" },
  { word: "mitigate",     def: "to make less severe or painful" },
  { word: "mollify",      def: "to soothe an angry person" },
  { word: "morose",       def: "gloomy and sullen" },
  { word: "munificent",   def: "extremely generous" },
  { word: "myriad",       def: "a huge number of something" },
  { word: "nadir",        def: "the lowest point" },
  { word: "nascent",      def: "just starting out; emerging" },
  { word: "nefarious",    def: "deeply wicked and evil" },
  { word: "neophyte",     def: "a beginner or newcomer" },
  { word: "nepotism",     def: "favoring relatives in hiring or power" },
  { word: "noisome",      def: "unpleasant, especially with a bad smell" },
  { word: "nostalgia",    def: "a longing for the past" },
  { word: "novel",        def: "new and original; not seen before" },
  { word: "obdurate",     def: "stubbornly refusing to change one's mind" },
  { word: "obfuscate",    def: "to make something hard to understand" },
  { word: "obsequious",   def: "overly eager to please; servile" },
  { word: "obstinate",    def: "stubborn and unyielding" },
  { word: "obtuse",       def: "slow to understand; dull" },
  { word: "officious",    def: "annoyingly eager to give orders or advice" },
  { word: "ominous",      def: "suggesting that something bad will happen" },
  { word: "onerous",      def: "burdensome and difficult to bear" },
  { word: "opaque",       def: "hard to see through or understand" },
  { word: "opulent",      def: "richly luxurious and lavish" },
  { word: "ostentatious", def: "showy in a way meant to impress" },
  { word: "pacify",       def: "to calm someone down" },
  { word: "palatable",    def: "acceptable in taste or in idea" },
  { word: "palliate",     def: "to ease the symptoms without curing" },
  { word: "panacea",      def: "a supposed cure for every problem" },
  { word: "paragon",      def: "a model of excellence" },
  { word: "pariah",       def: "a person rejected by society" },
  { word: "parsimonious", def: "extremely unwilling to spend or share" },
  { word: "partisan",     def: "strongly biased in favor of one side" },
  { word: "paucity",      def: "a very small amount; scarcity" },
  { word: "pedantic",     def: "fussy about small rules and details" },
  { word: "pejorative",   def: "expressing disapproval or contempt" },
  { word: "penchant",     def: "a strong liking for something" },
  { word: "perfidious",   def: "deceitful and untrustworthy" },
  { word: "perfunctory",  def: "done with little care, just to finish" },
  { word: "pernicious",   def: "having a harmful effect, often gradually" },
  { word: "perspicacious",def: "showing keen insight" },
  { word: "petulant",     def: "childishly irritable" },
  { word: "philanthropy", def: "the giving of money or help to others" },
  { word: "phlegmatic",   def: "calm and not easily upset" },
  { word: "pithy",        def: "short and full of meaning" },
  { word: "placate",      def: "to make someone less angry" },
  { word: "platitude",    def: "a tired statement said as if profound" },
  { word: "plausible",    def: "seeming reasonable or likely true" },
  { word: "plethora",     def: "an excess; too much of something" },
  { word: "polemic",      def: "a strong written or spoken attack" },
  { word: "pragmatic",    def: "dealing with things practically" },
  { word: "precarious",   def: "unstable and at risk of falling" },
  { word: "precipitate",  def: "to cause something to happen suddenly" },
  { word: "predilection", def: "a preference or special liking" },
  { word: "preempt",      def: "to act first to prevent something" },
  { word: "presage",      def: "to be a sign of something coming" },
  { word: "prescient",    def: "knowing things before they happen" },
  { word: "pretext",      def: "a false reason given to hide the real one" },
  { word: "prevaricate",  def: "to speak evasively to avoid the truth" },
  { word: "pristine",     def: "in original, perfect condition" },
  { word: "probity",      def: "complete honesty and integrity" },
  { word: "proclivity",   def: "a natural tendency, especially a bad one" },
  { word: "profligate",   def: "wastefully extravagant" },
  { word: "profuse",      def: "produced in great amounts" },
  { word: "proliferate",  def: "to increase rapidly in number" },
  { word: "propensity",   def: "a natural inclination to behave a way" },
  { word: "propitious",   def: "giving signs of a good outcome" },
  { word: "prosaic",      def: "ordinary and unimaginative" },
  { word: "protean",      def: "easily able to change form" },
  { word: "prudent",      def: "careful and wise in action" },
  { word: "puerile",      def: "childishly silly" },
  { word: "pugnacious",   def: "eager to fight or argue" },
  { word: "punctilious",  def: "very careful about small details of conduct" },
  { word: "pundit",       def: "an expert who comments publicly" },
  { word: "pusillanimous",def: "showing a cowardly lack of courage" },
  { word: "quaint",       def: "charmingly old-fashioned" },
  { word: "quell",        def: "to put an end to forcefully" },
  { word: "querulous",    def: "complaining in a whiny way" },
  { word: "quiescent",    def: "quiet and inactive" },
  { word: "quixotic",     def: "wildly idealistic and impractical" },
  { word: "rancor",       def: "long-lasting bitter resentment" },
  { word: "rapacious",    def: "extremely greedy, often violently so" },
  { word: "raucous",      def: "loud and rowdy" },
  { word: "rebuke",       def: "to scold sharply" },
  { word: "recalcitrant", def: "stubbornly refusing to obey" },
  { word: "recant",       def: "to publicly take back a statement" },
  { word: "reciprocate",  def: "to return the same action or feeling" },
  { word: "recondite",    def: "dealing with very obscure subjects" },
  { word: "redoubtable",  def: "deserving respect because formidable" },
  { word: "refute",       def: "to prove something to be wrong" },
  { word: "relegate",     def: "to send to a lower or worse place" },
  { word: "relinquish",   def: "to give up willingly" },
  { word: "remonstrate",  def: "to protest or argue against" },
  { word: "renege",       def: "to go back on a promise" },
  { word: "replete",      def: "filled with; well stocked" },
  { word: "reprehensible",def: "deserving strong criticism" },
  { word: "reproach",     def: "to express disapproval of someone" },
  { word: "repudiate",    def: "to reject something as invalid" },
  { word: "rescind",      def: "to officially cancel" },
  { word: "resolute",     def: "firm and determined" },
  { word: "reticent",     def: "not eager to share thoughts" },
  { word: "revere",       def: "to feel deep respect for" },
  { word: "rhetoric",     def: "the art of persuasive speaking or writing" },
  { word: "rife",         def: "very common; widespread, usually of bad things" },
  { word: "rudimentary",  def: "basic and underdeveloped" },
  { word: "ruminate",     def: "to think over something deeply" },
  { word: "sagacious",    def: "showing wise judgment" },
  { word: "salient",      def: "most noticeable or important" },
  { word: "sanguine",     def: "cheerfully optimistic" },
  { word: "sardonic",     def: "mocking in a bitter way" },
  { word: "scrupulous",   def: "careful to do what is right" },
  { word: "scurrilous",   def: "making damaging accusations" },
  { word: "sedulous",     def: "showing dedication and care" },
  { word: "serendipity",  def: "the luck of finding good things by chance" },
  { word: "servile",      def: "too eager to obey and please" },
  { word: "skeptical",    def: "doubtful and questioning" },
  { word: "slake",        def: "to quench, as thirst" },
  { word: "sobriquet",    def: "a person's nickname" },
  { word: "solicitous",   def: "showing caring concern" },
  { word: "soporific",    def: "tending to cause sleep" },
  { word: "specious",     def: "seeming true but actually false" },
  { word: "sporadic",     def: "happening at irregular intervals" },
  { word: "spurious",     def: "fake; not what it claims to be" },
  { word: "squander",     def: "to waste in a careless way" },
  { word: "staid",        def: "serious and not changing" },
  { word: "stoic",        def: "showing no emotion under stress" },
  { word: "stolid",       def: "calm, dependable, and unemotional" },
  { word: "strident",     def: "loud and harsh in sound or tone" },
  { word: "stymie",       def: "to prevent from making progress" },
  { word: "succinct",     def: "expressed clearly in few words" },
  { word: "supercilious", def: "behaving as if you feel superior" },
  { word: "superfluous",  def: "more than is needed" },
  { word: "surfeit",      def: "an excess; too much" },
  { word: "surreptitious",def: "done in a quiet, secret way" },
  { word: "sycophant",    def: "a person who flatters to gain favor" },
  { word: "taciturn",     def: "saying little; reserved" },
  { word: "tantamount",   def: "essentially the same as" },
  { word: "tedious",      def: "boringly long or slow" },
  { word: "temerity",     def: "rude boldness; nerve" },
  { word: "tenacious",    def: "holding on tightly; not giving up" },
  { word: "tenuous",      def: "weak and easily broken" },
  { word: "terse",        def: "brief and to the point, sometimes rudely" },
  { word: "timorous",     def: "shy and afraid" },
  { word: "torpid",       def: "sluggish and inactive" },
  { word: "tortuous",     def: "full of twists and turns" },
  { word: "tractable",    def: "easily managed or controlled" },
  { word: "transient",    def: "lasting only a short time" },
  { word: "trepidation",  def: "a feeling of fear about what's coming" },
  { word: "truculent",    def: "eager to argue or fight" },
  { word: "turpitude",    def: "wicked or shameful behavior" },
  { word: "ubiquitous",   def: "seeming to be everywhere at once" },
  { word: "umbrage",      def: "offense or annoyance" },
  { word: "unctuous",     def: "overly smooth and fake-friendly" },
  { word: "undulate",     def: "to move in a smooth wave-like motion" },
  { word: "unequivocal",  def: "leaving no doubt at all" },
  { word: "untenable",    def: "impossible to defend or maintain" },
  { word: "upbraid",      def: "to find fault and scold" },
  { word: "urbane",       def: "smooth, polished, and worldly" },
  { word: "usurp",        def: "to take power or position by force" },
  { word: "vacillate",    def: "to keep switching between options" },
  { word: "vacuous",      def: "empty of thought or meaning" },
  { word: "vapid",        def: "dull and lacking spirit" },
  { word: "venerable",    def: "respected because of age or wisdom" },
  { word: "veracity",     def: "truthfulness; accuracy" },
  { word: "verbose",      def: "using more words than needed" },
  { word: "vex",          def: "to annoy or worry someone" },
  { word: "vicarious",    def: "experienced through someone else" },
  { word: "vicissitude",  def: "a change in fortune, usually unwelcome" },
  { word: "vilify",       def: "to speak about with strong contempt" },
  { word: "vindicate",    def: "to clear someone of blame; to prove right" },
  { word: "vindictive",   def: "having a strong desire for revenge" },
  { word: "virtuoso",     def: "a person with exceptional skill" },
  { word: "vitriolic",    def: "filled with bitter criticism" },
  { word: "vituperative", def: "containing harsh, abusive language" },
  { word: "vivacious",    def: "lively and full of spirit" },
  { word: "vociferous",   def: "loud and forceful in speech" },
  { word: "voracious",    def: "having a huge appetite, for food or for anything" },
  { word: "wanton",       def: "deliberately and senselessly harmful" },
  { word: "wary",         def: "cautious about possible danger" },
  { word: "winsome",      def: "charming in an innocent way" },
  { word: "wistful",      def: "softly sad about something past or wished for" },
  { word: "wizened",      def: "shrunken and wrinkled with age" },
  { word: "zealous",      def: "showing great passion in pursuit of a cause" },
  { word: "zenith",       def: "the highest point of something" },
];

if (typeof module !== "undefined") module.exports = { STARTER_WORDS };
