// Starter vocabulary pack — ~390 college / SAT-tier words.
// Definitions are written in plain language (not copied from any source).
// Each word has a sample sentence to show meaning in context.
// Players can add their own words via the in-game editor.
const STARTER_WORDS = [
  { word: "aberration",   def: "something different from the usual or normal", sentence: "His outburst was a strange aberration from his usually calm behavior." },
  { word: "abscond",      def: "to run away suddenly, often in secret", sentence: "The treasurer absconded with the company's funds overnight." },
  { word: "abstemious",   def: "moderate, especially with food and drink", sentence: "She was abstemious at dinner, eating only a small salad." },
  { word: "abstruse",     def: "hard to understand", sentence: "The professor's abstruse explanation left the students completely confused." },
  { word: "accolade",     def: "an award or strong expression of praise", sentence: "The young pianist received many accolades after the concert." },
  { word: "acerbic",      def: "sharp or biting, especially in tone", sentence: "Her acerbic review made the chef want to quit cooking." },
  { word: "acquiesce",    def: "to agree without protest", sentence: "After much debate, he reluctantly acquiesced to their plan." },
  { word: "acrimony",     def: "bitterness or harshness in words or feelings", sentence: "The divorce was filled with acrimony on both sides." },
  { word: "acumen",       def: "the ability to make quick, smart judgments", sentence: "Her business acumen helped the startup grow tenfold." },
  { word: "admonish",     def: "to warn or scold gently", sentence: "The teacher gently admonished the student for talking in class." },
  { word: "aesthetic",    def: "relating to beauty or how something looks", sentence: "The garden was designed with both function and aesthetic in mind." },
  { word: "affable",      def: "friendly and easy to talk to", sentence: "Our affable neighbor invites everyone over for barbecues." },
  { word: "aggrandize",   def: "to make something seem greater than it is", sentence: "Politicians often aggrandize their accomplishments before elections." },
  { word: "alacrity",     def: "cheerful eagerness or quickness", sentence: "She accepted the invitation with alacrity and started packing." },
  { word: "ambiguous",    def: "having more than one possible meaning", sentence: "His ambiguous answer could be read as either yes or no." },
  { word: "ambivalent",   def: "having mixed feelings about something", sentence: "I feel ambivalent about moving — excited but also sad to leave." },
  { word: "ameliorate",   def: "to make a bad situation better", sentence: "The new medication should ameliorate her symptoms within days." },
  { word: "amicable",     def: "friendly and without conflict", sentence: "The two companies reached an amicable settlement out of court." },
  { word: "anachronism",  def: "something out of its proper time period", sentence: "A flip phone in 2026 feels like a strange anachronism." },
  { word: "analogous",    def: "similar in some way that allows comparison", sentence: "The brain is often called analogous to a computer." },
  { word: "anomaly",      def: "something that doesn't fit the pattern", sentence: "The single failed test was an anomaly in an otherwise perfect run." },
  { word: "antagonize",   def: "to make someone hostile toward you", sentence: "Don't antagonize the bear by getting too close." },
  { word: "antipathy",    def: "a strong feeling of dislike", sentence: "She felt deep antipathy toward bullies of any kind." },
  { word: "apathy",       def: "a lack of interest or feeling", sentence: "Voter apathy led to the lowest turnout in decades." },
  { word: "apocryphal",   def: "of doubtful authenticity, though widely told", sentence: "That story about Washington's cherry tree is apocryphal." },
  { word: "approbation",  def: "official approval or praise", sentence: "The proposal won the unanimous approbation of the board." },
  { word: "arbitrary",    def: "based on personal whim, not reason", sentence: "The rule felt arbitrary, with no real reason behind it." },
  { word: "arcane",       def: "secret, known only to a few", sentence: "Tax law contains many arcane rules that confuse even experts." },
  { word: "archaic",      def: "very old or old-fashioned", sentence: "His archaic dial-up modem couldn't load modern websites." },
  { word: "ardent",       def: "full of strong feeling or passion", sentence: "She is an ardent supporter of public libraries." },
  { word: "arduous",      def: "requiring great effort; very difficult", sentence: "Climbing the mountain was an arduous, three-day journey." },
  { word: "ascetic",      def: "someone who lives with strict self-denial", sentence: "The ascetic monk lived in a bare stone cell." },
  { word: "assiduous",    def: "showing great care and persistence", sentence: "Her assiduous note-taking helped her ace every exam." },
  { word: "assuage",      def: "to make an unpleasant feeling less intense", sentence: "A kind word can assuage even deep grief." },
  { word: "astute",       def: "clever and quick to understand", sentence: "His astute observation revealed what everyone else had missed." },
  { word: "audacious",    def: "boldly daring, sometimes recklessly so", sentence: "Her audacious plan to swim the Channel surprised her family." },
  { word: "augment",      def: "to make something larger or stronger", sentence: "He took a second job to augment his income." },
  { word: "auspicious",   def: "showing signs of future success", sentence: "The clear sky was an auspicious start to the wedding day." },
  { word: "austere",      def: "strict, plain, or severe", sentence: "The austere classroom had nothing but desks and a blackboard." },
  { word: "avarice",      def: "extreme greed for wealth", sentence: "His avarice grew with every dollar he earned." },
  { word: "aversion",     def: "a strong dislike or wish to avoid", sentence: "She has a strong aversion to spicy food." },
  { word: "banal",        def: "boringly common or unoriginal", sentence: "The movie's banal dialogue put us to sleep." },
  { word: "belie",        def: "to give a false impression of", sentence: "Her smile belied the sadness she felt inside." },
  { word: "belligerent",  def: "eager to fight or argue", sentence: "The belligerent customer demanded to see the manager." },
  { word: "benevolent",   def: "kind and wanting to do good", sentence: "The benevolent stranger paid for our entire meal." },
  { word: "benign",       def: "gentle and harmless", sentence: "Thankfully, the lump turned out to be benign." },
  { word: "bequeath",     def: "to leave something to someone in a will", sentence: "She bequeathed her vintage records to her grandson." },
  { word: "blatant",      def: "completely obvious, in a bad way", sentence: "His blatant lying eventually cost him his job." },
  { word: "bolster",      def: "to support or strengthen", sentence: "New evidence will bolster the case against the suspect." },
  { word: "bombastic",    def: "using grand language to sound important", sentence: "The mayor gave a bombastic speech full of grand promises." },
  { word: "brevity",      def: "shortness, especially of speech or writing", sentence: "The professor valued brevity in student essays." },
  { word: "burgeon",      def: "to grow or expand rapidly", sentence: "The town's population is burgeoning thanks to remote workers." },
  { word: "cacophony",    def: "a harsh mixture of loud sounds", sentence: "A cacophony of horns filled the rush-hour street." },
  { word: "cajole",       def: "to coax with flattery or gentle pressure", sentence: "She had to cajole her brother into doing his chores." },
  { word: "callous",      def: "showing no concern for others' feelings", sentence: "His callous remarks about the layoffs upset everyone." },
  { word: "candor",       def: "honesty and openness in speech", sentence: "I appreciate your candor about the project's risks." },
  { word: "capricious",   def: "changing one's mind suddenly and often", sentence: "The capricious weather changed from sunny to stormy in an hour." },
  { word: "castigate",    def: "to scold or criticize harshly", sentence: "The coach castigated the team for not hustling." },
  { word: "caustic",      def: "sharply sarcastic; able to burn or eat away", sentence: "Her caustic wit could leave anyone speechless." },
  { word: "censure",      def: "to express strong disapproval, often formally", sentence: "The senator faced censure for breaking ethics rules." },
  { word: "chagrin",      def: "a feeling of embarrassment or annoyance", sentence: "Much to my chagrin, I forgot the most important slide." },
  { word: "charlatan",    def: "a person falsely claiming special knowledge", sentence: "The so-called doctor turned out to be a charlatan." },
  { word: "chastise",     def: "to punish or scold severely", sentence: "Mom chastised us for tracking mud through the house." },
  { word: "chicanery",    def: "the use of clever tricks to deceive", sentence: "The lawyer was disbarred for his chicanery in court." },
  { word: "circuitous",   def: "longer than the most direct way", sentence: "We took a circuitous route to avoid the traffic." },
  { word: "circumspect",  def: "careful to consider all the consequences", sentence: "She is circumspect when sharing personal information online." },
  { word: "clandestine",  def: "kept secret, often for an improper reason", sentence: "Their clandestine meetings were eventually discovered." },
  { word: "coalesce",     def: "to come together and form one whole", sentence: "The protesters began to coalesce around a single demand." },
  { word: "cogent",       def: "clear, logical, and convincing", sentence: "He presented a cogent argument for the policy change." },
  { word: "complacent",   def: "too pleased with yourself to try harder", sentence: "After a few wins, the team grew complacent and started losing." },
  { word: "concur",       def: "to agree with someone", sentence: "I concur with the doctor's recommendation." },
  { word: "condone",      def: "to accept or allow behavior that is wrong", sentence: "The school does not condone cheating in any form." },
  { word: "conflagration",def: "an extensive and destructive fire", sentence: "The conflagration destroyed three city blocks." },
  { word: "congenial",    def: "pleasant and agreeable to be around", sentence: "The host created a congenial atmosphere at her dinner party." },
  { word: "conjecture",   def: "a guess based on incomplete information", sentence: "Without evidence, his theory is mere conjecture." },
  { word: "consensus",    def: "general agreement among a group", sentence: "After hours of talks, the committee reached a consensus." },
  { word: "contentious",  def: "likely to cause an argument", sentence: "The contentious issue divided the community." },
  { word: "contrite",     def: "feeling deeply sorry for what you did", sentence: "His contrite apology brought tears to her eyes." },
  { word: "conundrum",    def: "a confusing or difficult problem", sentence: "Solving the budget shortfall was a tricky conundrum." },
  { word: "copious",      def: "very large in amount", sentence: "She took copious notes during the lecture." },
  { word: "corroborate",  def: "to confirm or support with evidence", sentence: "Two witnesses can corroborate his alibi." },
  { word: "credulous",    def: "too ready to believe things", sentence: "His credulous nephew believed every tall tale." },
  { word: "cryptic",      def: "mysterious and hard to understand", sentence: "Her cryptic text left him guessing all evening." },
  { word: "cursory",      def: "quick and not thorough", sentence: "A cursory glance at the report missed the key error." },
  { word: "dearth",       def: "a scarcity or lack of something", sentence: "There's a dearth of affordable housing in this city." },
  { word: "debacle",      def: "a sudden and humiliating failure", sentence: "The launch was a debacle — three crashes in the first hour." },
  { word: "decorum",      def: "behavior that is polite and proper", sentence: "Please maintain decorum during the formal ceremony." },
  { word: "deference",    def: "respectful yielding to another's wishes", sentence: "Out of deference to her elder, he gave up his seat." },
  { word: "deleterious",  def: "harmful, often in a subtle way", sentence: "Smoking has deleterious effects on lung health." },
  { word: "demure",       def: "reserved, modest, and shy", sentence: "She gave a demure smile and looked at her shoes." },
  { word: "denigrate",    def: "to criticize unfairly; to put down", sentence: "Don't denigrate his efforts — he's only just starting." },
  { word: "deride",       def: "to make fun of in a cruel way", sentence: "Children sometimes deride classmates who dress differently." },
  { word: "desiccate",    def: "to dry out completely", sentence: "The hot wind desiccated the leaves to crumbling brown." },
  { word: "despot",       def: "a ruler with absolute and harsh power", sentence: "The despot ruled through fear and crushed all dissent." },
  { word: "diatribe",     def: "a long, angry, critical speech", sentence: "His diatribe against modern art lasted an hour." },
  { word: "didactic",     def: "intended to teach, sometimes too much so", sentence: "The novel is so didactic it reads like a lecture." },
  { word: "diffident",    def: "shy and lacking self-confidence", sentence: "The diffident new hire rarely spoke in meetings." },
  { word: "digress",      def: "to wander off the main topic", sentence: "Sorry to digress, but did you see last night's game?" },
  { word: "dilatory",     def: "slow to act, causing delay", sentence: "His dilatory replies frustrated the whole team." },
  { word: "discordant",   def: "harsh and not in harmony", sentence: "The choir made a discordant noise during warm-ups." },
  { word: "disparage",    def: "to speak of as not worth much", sentence: "Critics disparaged the painting as childish." },
  { word: "disparate",    def: "very different and hard to compare", sentence: "It's hard to draw conclusions from such disparate sources." },
  { word: "dissemble",    def: "to hide your true feelings or motives", sentence: "She tried to dissemble her disappointment with a smile." },
  { word: "dogmatic",     def: "stating opinions as if they were facts", sentence: "His dogmatic views left no room for discussion." },
  { word: "dubious",      def: "doubtful; questionable", sentence: "I'm dubious of any deal that sounds too good to be true." },
  { word: "duplicity",    def: "deceitful double-dealing", sentence: "His duplicity was exposed when both contracts came to light." },
  { word: "ebullient",    def: "cheerful and full of energy", sentence: "She was ebullient after winning the science fair." },
  { word: "eclectic",     def: "drawing from a wide variety of sources", sentence: "His eclectic taste in music includes jazz, punk, and folk." },
  { word: "edify",        def: "to teach in a way that improves character", sentence: "The documentary aims to edify rather than entertain." },
  { word: "efficacy",     def: "the power to produce a desired result", sentence: "Researchers are testing the efficacy of the new vaccine." },
  { word: "effusive",     def: "showing feeling in an unrestrained way", sentence: "Her effusive thanks embarrassed the modest helper." },
  { word: "egregious",    def: "outstandingly bad; shocking", sentence: "That was an egregious error in the live broadcast." },
  { word: "elated",       def: "extremely happy and excited", sentence: "We were elated when the adoption was finally approved." },
  { word: "elicit",       def: "to draw out a response or reaction", sentence: "Her question elicited a long pause and then a quiet answer." },
  { word: "eloquent",     def: "fluent and persuasive in speaking", sentence: "The senator's eloquent speech moved many to tears." },
  { word: "elucidate",    def: "to make something clear; to explain", sentence: "Could you elucidate what you meant by that comment?" },
  { word: "emaciated",    def: "extremely thin from hunger or illness", sentence: "The lost hiker was emaciated when finally rescued." },
  { word: "embellish",    def: "to add decorative or invented detail", sentence: "He likes to embellish his fishing stories with bigger fish." },
  { word: "empirical",    def: "based on observation, not theory", sentence: "Their conclusion is backed by years of empirical research." },
  { word: "emulate",      def: "to imitate in order to equal or surpass", sentence: "Many young writers try to emulate their literary heroes." },
  { word: "enervate",     def: "to drain of energy or vitality", sentence: "The summer heat enervated even the strongest workers." },
  { word: "enigmatic",    def: "difficult to interpret; mysterious", sentence: "Her enigmatic smile gave nothing away." },
  { word: "ephemeral",    def: "lasting only a very short time", sentence: "Cherry blossoms are beautiful but ephemeral." },
  { word: "equanimity",   def: "calmness, especially under stress", sentence: "He faced the bad news with quiet equanimity." },
  { word: "equivocal",    def: "vague and open to more than one meaning", sentence: "His equivocal response left us unsure where he stood." },
  { word: "erudite",      def: "showing great knowledge from study", sentence: "The erudite scholar quoted poets in five languages." },
  { word: "eschew",       def: "to deliberately avoid", sentence: "The chef eschews shortcuts in favor of traditional methods." },
  { word: "esoteric",     def: "understood by only a small group", sentence: "His blog covers esoteric topics most readers never search for." },
  { word: "ethereal",     def: "delicate and light, almost otherworldly", sentence: "Her ethereal voice seemed to float above the orchestra." },
  { word: "euphemism",    def: "a mild word used in place of a harsh one", sentence: "'Passed away' is a euphemism for died." },
  { word: "exacerbate",   def: "to make a bad situation worse", sentence: "Stress can exacerbate chronic health conditions." },
  { word: "exemplary",    def: "serving as an excellent example", sentence: "Her exemplary conduct earned a special school award." },
  { word: "exonerate",    def: "to clear from blame or guilt", sentence: "New DNA evidence helped exonerate the wrongly accused." },
  { word: "expedient",    def: "useful for a quick result, even if not ideal", sentence: "Taking the back roads was expedient given the traffic." },
  { word: "extol",        def: "to praise enthusiastically", sentence: "The coach extolled the virtues of practice and patience." },
  { word: "extraneous",   def: "not relevant; unnecessary", sentence: "Cut any extraneous details from your essay." },
  { word: "facetious",    def: "joking, often when seriousness is expected", sentence: "Don't take him seriously — he's just being facetious." },
  { word: "fallacious",   def: "based on a mistaken belief", sentence: "His fallacious reasoning fooled no one in the room." },
  { word: "fastidious",   def: "very attentive to detail; hard to please", sentence: "She is fastidious about keeping her desk perfectly organized." },
  { word: "fatuous",      def: "silly and pointless", sentence: "His fatuous remark earned eye-rolls from the audience." },
  { word: "fervent",      def: "showing intense passion or sincerity", sentence: "She is a fervent advocate for animal rights." },
  { word: "flagrant",     def: "openly and obviously offensive", sentence: "His flagrant disregard for the rules got him ejected." },
  { word: "florid",       def: "overly fancy or elaborate", sentence: "The author's florid prose felt overdone." },
  { word: "fortuitous",   def: "happening by lucky chance", sentence: "Their fortuitous meeting at the airport led to lifelong friendship." },
  { word: "frugal",       def: "careful with money and resources", sentence: "Her frugal habits helped her retire early." },
  { word: "furtive",      def: "secret and sneaky", sentence: "He cast a furtive glance toward the exit." },
  { word: "garrulous",    def: "talking too much, especially about small things", sentence: "The garrulous taxi driver shared his life story in ten minutes." },
  { word: "germane",      def: "relevant to the topic at hand", sentence: "Please keep your comments germane to the agenda." },
  { word: "glib",         def: "speaking smoothly but insincerely", sentence: "His glib answers couldn't disguise his lack of preparation." },
  { word: "grandiose",    def: "impressive in a self-important way", sentence: "Their grandiose plans for the renovation never materialized." },
  { word: "gratuitous",   def: "uncalled for; without good reason", sentence: "The film had gratuitous violence that added nothing to the plot." },
  { word: "gregarious",   def: "enjoying the company of others", sentence: "The gregarious puppy greets every visitor with a tail wag." },
  { word: "harangue",     def: "a long, scolding speech", sentence: "The candidate launched into a harangue about taxes." },
  { word: "hackneyed",    def: "overused and no longer interesting", sentence: "The script relies on hackneyed jokes from the 90s." },
  { word: "haughty",      def: "arrogantly proud", sentence: "She gave him a haughty look and walked away." },
  { word: "hegemony",     def: "leadership or dominance over others", sentence: "The empire's hegemony lasted for centuries." },
  { word: "heretic",      def: "someone who holds a forbidden belief", sentence: "He was branded a heretic for questioning the doctrine." },
  { word: "hubris",       def: "excessive pride that leads to a fall", sentence: "His hubris led him to attempt the climb without a guide." },
  { word: "iconoclast",   def: "someone who attacks cherished beliefs", sentence: "The iconoclast artist tore down conventions of portraiture." },
  { word: "idiosyncrasy", def: "a peculiar habit unique to a person", sentence: "Always carrying a lucky pen is one of her idiosyncrasies." },
  { word: "imminent",     def: "about to happen at any moment", sentence: "Storm clouds suggested rain was imminent." },
  { word: "impecunious",  def: "having very little money", sentence: "The impecunious student lived on instant noodles." },
  { word: "imperious",    def: "demanding obedience in a haughty way", sentence: "Her imperious tone made the waiter bristle." },
  { word: "impetuous",    def: "acting suddenly without thinking", sentence: "His impetuous decision to quit surprised everyone." },
  { word: "implacable",   def: "impossible to calm or please", sentence: "Her implacable anger never softened with time." },
  { word: "impugn",       def: "to challenge as false or dishonest", sentence: "I would not impugn his honesty without solid proof." },
  { word: "inane",        def: "silly and lacking meaning", sentence: "Stop wasting time on these inane internet quizzes." },
  { word: "incessant",    def: "never stopping; continual", sentence: "The incessant rain ruined our vacation plans." },
  { word: "inchoate",     def: "just beginning; not yet fully formed", sentence: "His ideas were still inchoate but full of promise." },
  { word: "incisive",     def: "sharp and clear in thought", sentence: "Her incisive questions exposed every weak point in the plan." },
  { word: "incongruous",  def: "out of place; not fitting in", sentence: "The tuxedo looked incongruous at a backyard picnic." },
  { word: "indolent",     def: "lazy and avoiding effort", sentence: "The indolent cat spent the entire afternoon on the windowsill." },
  { word: "ineffable",    def: "too great or extreme to be expressed", sentence: "The view from the summit was ineffable beauty." },
  { word: "inept",        def: "having no skill at something", sentence: "His inept handling of the meeting embarrassed the company." },
  { word: "inexorable",   def: "impossible to stop or change", sentence: "The inexorable march of time turns children into adults." },
  { word: "ingenuous",    def: "innocent, trusting, and unsophisticated", sentence: "Her ingenuous question about the surprise gave it away." },
  { word: "inimical",     def: "harmful or hostile", sentence: "The harsh climate is inimical to most crops." },
  { word: "innocuous",    def: "harmless and unlikely to offend", sentence: "His innocuous comment somehow offended her." },
  { word: "insidious",    def: "harmful in a slow, hidden way", sentence: "Carbon monoxide is insidious — odorless but deadly." },
  { word: "insipid",      def: "lacking flavor, interest, or vigor", sentence: "The soup was insipid and needed a lot of salt." },
  { word: "intransigent", def: "refusing to change one's position", sentence: "His intransigent position blocked any compromise." },
  { word: "inundate",     def: "to flood; to overwhelm with too much", sentence: "Floods inundated the entire valley overnight." },
  { word: "inveterate",   def: "long-established and unlikely to change", sentence: "He's an inveterate procrastinator — every paper is last-minute." },
  { word: "irascible",    def: "easily angered", sentence: "Their irascible boss snapped at the smallest mistake." },
  { word: "itinerant",    def: "traveling from place to place for work", sentence: "The itinerant musician played in a different town each week." },
  { word: "jocular",      def: "fond of joking and good humor", sentence: "His jocular manner kept the long meeting from getting tense." },
  { word: "juxtapose",    def: "to place side by side for comparison", sentence: "The exhibit juxtaposes modern art with medieval tapestries." },
  { word: "kinetic",      def: "relating to motion or energy of motion", sentence: "The kinetic sculpture spins gently in the breeze." },
  { word: "laconic",      def: "using very few words", sentence: "The detective's laconic replies revealed nothing." },
  { word: "languid",      def: "slow and lacking energy", sentence: "She moved with a languid grace through the heat." },
  { word: "largesse",     def: "generosity, especially by the wealthy", sentence: "The community thrived thanks to the founder's largesse." },
  { word: "latent",       def: "hidden but able to develop", sentence: "The talent was latent until a great teacher drew it out." },
  { word: "laudable",     def: "deserving praise", sentence: "His laudable effort to learn Korean impressed his colleagues." },
  { word: "lethargic",    def: "sluggish and lacking energy", sentence: "After Thanksgiving dinner, everyone felt lethargic on the couch." },
  { word: "levity",       def: "humor or lightness, often where unwelcome", sentence: "A bit of levity helped lift the somber mood." },
  { word: "loquacious",   def: "very talkative", sentence: "Our loquacious aunt can talk for hours about her garden." },
  { word: "lucid",        def: "easy to understand; clear-minded", sentence: "Grandpa was lucid and sharp despite his age." },
  { word: "lugubrious",   def: "looking or sounding sad in a comical way", sentence: "His lugubrious face made even good news sound sad." },
  { word: "magnanimous",  def: "generous, especially toward rivals", sentence: "The champion was magnanimous in victory, praising her opponent." },
  { word: "malevolent",   def: "wishing harm on others", sentence: "The story's villain had a malevolent grin." },
  { word: "malign",       def: "to speak badly of someone unfairly", sentence: "Don't malign him before you hear his side." },
  { word: "malleable",    def: "easily shaped or influenced", sentence: "Children's minds are remarkably malleable." },
  { word: "maverick",     def: "an independent thinker who breaks rules", sentence: "The maverick scientist refused to follow the established theory." },
  { word: "mendacious",   def: "habitually lying", sentence: "His mendacious testimony fell apart on cross-examination." },
  { word: "mercurial",    def: "changing mood quickly and unpredictably", sentence: "Her mercurial moods kept her family on edge." },
  { word: "meticulous",   def: "extremely careful about small details", sentence: "The clockmaker's meticulous work took weeks per piece." },
  { word: "mitigate",     def: "to make less severe or painful", sentence: "Wearing sunscreen can mitigate sun damage to skin." },
  { word: "mollify",      def: "to soothe an angry person", sentence: "An apology and free dessert mollified the unhappy guest." },
  { word: "morose",       def: "gloomy and sullen", sentence: "He grew morose after losing the championship game." },
  { word: "munificent",   def: "extremely generous", sentence: "The munificent donor funded the new library wing." },
  { word: "myriad",       def: "a huge number of something", sentence: "There are myriad reasons to start exercising today." },
  { word: "nadir",        def: "the lowest point", sentence: "His career hit its nadir when he was demoted twice." },
  { word: "nascent",      def: "just starting out; emerging", sentence: "The nascent startup had only six employees." },
  { word: "nefarious",    def: "deeply wicked and evil", sentence: "Police uncovered a nefarious scheme to defraud seniors." },
  { word: "neophyte",     def: "a beginner or newcomer", sentence: "As a neophyte, she asked questions everyone else was afraid to." },
  { word: "nepotism",     def: "favoring relatives in hiring or power", sentence: "Hiring his cousin was textbook nepotism." },
  { word: "noisome",      def: "unpleasant, especially with a bad smell", sentence: "A noisome smell drifted up from the alley." },
  { word: "nostalgia",    def: "a longing for the past", sentence: "Hearing old radio jingles fills her with nostalgia." },
  { word: "novel",        def: "new and original; not seen before", sentence: "The chef tried a novel combination of chocolate and chili." },
  { word: "obdurate",     def: "stubbornly refusing to change one's mind", sentence: "His obdurate refusal to apologize cost him the friendship." },
  { word: "obfuscate",    def: "to make something hard to understand", sentence: "Lawyers can obfuscate the truth with technical jargon." },
  { word: "obsequious",   def: "overly eager to please; servile", sentence: "The obsequious clerk agreed with every word the boss said." },
  { word: "obstinate",    def: "stubborn and unyielding", sentence: "The obstinate child refused to wear her coat." },
  { word: "obtuse",       def: "slow to understand; dull", sentence: "Stop being obtuse — you know exactly what I mean." },
  { word: "officious",    def: "annoyingly eager to give orders or advice", sentence: "The officious neighbor reminded us to mow our lawn weekly." },
  { word: "ominous",      def: "suggesting that something bad will happen", sentence: "Ominous clouds gathered before the tornado warning." },
  { word: "onerous",      def: "burdensome and difficult to bear", sentence: "Caring for an elderly parent can be an onerous duty." },
  { word: "opaque",       def: "hard to see through or understand", sentence: "The contract's language was deliberately opaque." },
  { word: "opulent",      def: "richly luxurious and lavish", sentence: "The opulent ballroom dripped with crystal and gold leaf." },
  { word: "ostentatious", def: "showy in a way meant to impress", sentence: "His ostentatious diamond watch turned heads at the meeting." },
  { word: "pacify",       def: "to calm someone down", sentence: "She tried to pacify the crying baby with a soft song." },
  { word: "palatable",    def: "acceptable in taste or in idea", sentence: "We made the medicine palatable by mixing it with juice." },
  { word: "palliate",     def: "to ease the symptoms without curing", sentence: "Aspirin can palliate the pain but won't cure the illness." },
  { word: "panacea",      def: "a supposed cure for every problem", sentence: "Exercise is no panacea, but it helps with many problems." },
  { word: "paragon",      def: "a model of excellence", sentence: "She is a paragon of patience with her young students." },
  { word: "pariah",       def: "a person rejected by society", sentence: "He became a pariah at the office after the scandal." },
  { word: "parsimonious", def: "extremely unwilling to spend or share", sentence: "The parsimonious uncle reused tea bags three times." },
  { word: "partisan",     def: "strongly biased in favor of one side", sentence: "The article was so partisan it ignored the other side." },
  { word: "paucity",      def: "a very small amount; scarcity", sentence: "There is a paucity of evidence to support that theory." },
  { word: "pedantic",     def: "fussy about small rules and details", sentence: "His pedantic corrections made conversation exhausting." },
  { word: "pejorative",   def: "expressing disapproval or contempt", sentence: "'Nerd' was once pejorative but now feels almost affectionate." },
  { word: "penchant",     def: "a strong liking for something", sentence: "She has a penchant for old black-and-white movies." },
  { word: "perfidious",   def: "deceitful and untrustworthy", sentence: "His perfidious betrayal of his partner shocked everyone." },
  { word: "perfunctory",  def: "done with little care, just to finish", sentence: "The waiter's perfunctory greeting suggested a long shift." },
  { word: "pernicious",   def: "having a harmful effect, often gradually", sentence: "The pernicious rumor slowly destroyed her reputation." },
  { word: "perspicacious",def: "showing keen insight", sentence: "Her perspicacious analysis revealed the company's hidden weakness." },
  { word: "petulant",     def: "childishly irritable", sentence: "The petulant child threw the toy across the room." },
  { word: "philanthropy", def: "the giving of money or help to others", sentence: "His philanthropy funded scholarships for thousands." },
  { word: "phlegmatic",   def: "calm and not easily upset", sentence: "Her phlegmatic boss never seemed flustered by deadlines." },
  { word: "pithy",        def: "short and full of meaning", sentence: "He answered the question with a pithy one-liner." },
  { word: "placate",      def: "to make someone less angry", sentence: "A bouquet of flowers helped placate his angry friend." },
  { word: "platitude",    def: "a tired statement said as if profound", sentence: "'Everything happens for a reason' is a tired platitude." },
  { word: "plausible",    def: "seeming reasonable or likely true", sentence: "Her excuse for being late was plausible enough." },
  { word: "plethora",     def: "an excess; too much of something", sentence: "A plethora of options can make choosing harder." },
  { word: "polemic",      def: "a strong written or spoken attack", sentence: "The book is a polemic against modern schooling." },
  { word: "pragmatic",    def: "dealing with things practically", sentence: "She took a pragmatic approach and chose the cheapest option that worked." },
  { word: "precarious",   def: "unstable and at risk of falling", sentence: "The vase sat in a precarious spot near the edge." },
  { word: "precipitate",  def: "to cause something to happen suddenly", sentence: "His outburst precipitated a heated argument." },
  { word: "predilection", def: "a preference or special liking", sentence: "She has a predilection for spicy food and strong coffee." },
  { word: "preempt",      def: "to act first to prevent something", sentence: "The president preempted the regular show with a news bulletin." },
  { word: "presage",      def: "to be a sign of something coming", sentence: "Dark clouds presaged the coming storm." },
  { word: "prescient",    def: "knowing things before they happen", sentence: "His prescient warnings about the bubble were ignored." },
  { word: "pretext",      def: "a false reason given to hide the real one", sentence: "He used the report as a pretext to leave early." },
  { word: "prevaricate",  def: "to speak evasively to avoid the truth", sentence: "Stop prevaricating and tell me what really happened." },
  { word: "pristine",     def: "in original, perfect condition", sentence: "The vintage car was kept in pristine condition." },
  { word: "probity",      def: "complete honesty and integrity", sentence: "The judge was known for her unquestionable probity." },
  { word: "proclivity",   def: "a natural tendency, especially a bad one", sentence: "His proclivity for taking risks made him a daring investor." },
  { word: "profligate",   def: "wastefully extravagant", sentence: "Profligate spending eventually drained the family fortune." },
  { word: "profuse",      def: "produced in great amounts", sentence: "She offered profuse apologies for the misunderstanding." },
  { word: "proliferate",  def: "to increase rapidly in number", sentence: "Coffee shops have proliferated in this neighborhood." },
  { word: "propensity",   def: "a natural inclination to behave a way", sentence: "He has a propensity to interrupt during meetings." },
  { word: "propitious",   def: "giving signs of a good outcome", sentence: "The fortune teller called it a propitious day for travel." },
  { word: "prosaic",      def: "ordinary and unimaginative", sentence: "His prosaic description of Paris missed all the magic." },
  { word: "protean",      def: "easily able to change form", sentence: "The actor's protean talent let him play any role." },
  { word: "prudent",      def: "careful and wise in action", sentence: "It's prudent to save some money for emergencies." },
  { word: "puerile",      def: "childishly silly", sentence: "The puerile prank wasn't funny, just immature." },
  { word: "pugnacious",   def: "eager to fight or argue", sentence: "The pugnacious puppy challenged dogs three times its size." },
  { word: "punctilious",  def: "very careful about small details of conduct", sentence: "She is punctilious about thank-you notes after every gift." },
  { word: "pundit",       def: "an expert who comments publicly", sentence: "Every political pundit predicted a different outcome." },
  { word: "pusillanimous",def: "showing a cowardly lack of courage", sentence: "His pusillanimous retreat from the debate disappointed his fans." },
  { word: "quaint",       def: "charmingly old-fashioned", sentence: "We stayed in a quaint cottage with a thatched roof." },
  { word: "quell",        def: "to put an end to forcefully", sentence: "The captain managed to quell the rebellion before it spread." },
  { word: "querulous",    def: "complaining in a whiny way", sentence: "The querulous toddler whined about every meal." },
  { word: "quiescent",    def: "quiet and inactive", sentence: "The volcano has been quiescent for two hundred years." },
  { word: "quixotic",     def: "wildly idealistic and impractical", sentence: "His quixotic plan to row across the ocean drew warnings." },
  { word: "rancor",       def: "long-lasting bitter resentment", sentence: "The two families nursed rancor for three generations." },
  { word: "rapacious",    def: "extremely greedy, often violently so", sentence: "Rapacious traders bought up every house in the neighborhood." },
  { word: "raucous",      def: "loud and rowdy", sentence: "A raucous crowd cheered the band on stage." },
  { word: "rebuke",       def: "to scold sharply", sentence: "The teacher's gentle rebuke stopped the whispering." },
  { word: "recalcitrant", def: "stubbornly refusing to obey", sentence: "The recalcitrant donkey refused to budge from the path." },
  { word: "recant",       def: "to publicly take back a statement", sentence: "Under pressure, the witness recanted her testimony." },
  { word: "reciprocate",  def: "to return the same action or feeling", sentence: "She brought soup, and he reciprocated with home-baked bread." },
  { word: "recondite",    def: "dealing with very obscure subjects", sentence: "His recondite knowledge of medieval coins impressed the curator." },
  { word: "redoubtable",  def: "deserving respect because formidable", sentence: "Our redoubtable goalie has shut out every team this season." },
  { word: "refute",       def: "to prove something to be wrong", sentence: "New data refutes the older theory." },
  { word: "relegate",     def: "to send to a lower or worse place", sentence: "The losing team was relegated to a lower division." },
  { word: "relinquish",   def: "to give up willingly", sentence: "She had to relinquish her seat to a senior passenger." },
  { word: "remonstrate",  def: "to protest or argue against", sentence: "Parents remonstrated with the principal about the new rules." },
  { word: "renege",       def: "to go back on a promise", sentence: "He reneged on the deal at the last minute." },
  { word: "replete",      def: "filled with; well stocked", sentence: "The valley was replete with wildflowers in spring." },
  { word: "reprehensible",def: "deserving strong criticism", sentence: "Cheating on a friend is reprehensible behavior." },
  { word: "reproach",     def: "to express disapproval of someone", sentence: "His mother's quiet reproach made him feel worse than yelling." },
  { word: "repudiate",    def: "to reject something as invalid", sentence: "The candidate publicly repudiated the endorsement." },
  { word: "rescind",      def: "to officially cancel", sentence: "The company rescinded the job offer after the background check." },
  { word: "resolute",     def: "firm and determined", sentence: "She was resolute in her decision to study abroad." },
  { word: "reticent",     def: "not eager to share thoughts", sentence: "He is reticent about his time in the military." },
  { word: "revere",       def: "to feel deep respect for", sentence: "Students revered the old professor for her wisdom." },
  { word: "rhetoric",     def: "the art of persuasive speaking or writing", sentence: "Beyond the rhetoric, the policy offered little substance." },
  { word: "rife",         def: "very common; widespread, usually of bad things", sentence: "The neighborhood is rife with rumors about the new owner." },
  { word: "rudimentary",  def: "basic and underdeveloped", sentence: "His rudimentary Spanish was enough to order coffee." },
  { word: "ruminate",     def: "to think over something deeply", sentence: "She likes to ruminate over decisions for days." },
  { word: "sagacious",    def: "showing wise judgment", sentence: "His sagacious advice has guided me through tough times." },
  { word: "salient",      def: "most noticeable or important", sentence: "Let me highlight the salient points of the report." },
  { word: "sanguine",     def: "cheerfully optimistic", sentence: "Despite setbacks, she remains sanguine about the project." },
  { word: "sardonic",     def: "mocking in a bitter way", sentence: "His sardonic comment about the meeting made me laugh." },
  { word: "scrupulous",   def: "careful to do what is right", sentence: "She is scrupulous about returning library books on time." },
  { word: "scurrilous",   def: "making damaging accusations", sentence: "The scurrilous gossip column was eventually sued." },
  { word: "sedulous",     def: "showing dedication and care", sentence: "His sedulous practice paid off at the recital." },
  { word: "serendipity",  def: "the luck of finding good things by chance", sentence: "Through pure serendipity, I found my missing ring at the cafe." },
  { word: "servile",      def: "too eager to obey and please", sentence: "His servile manner toward the boss embarrassed his coworkers." },
  { word: "skeptical",    def: "doubtful and questioning", sentence: "I'm skeptical of any miracle weight-loss claim." },
  { word: "slake",        def: "to quench, as thirst", sentence: "A cold lemonade slaked our thirst after the hike." },
  { word: "sobriquet",    def: "a person's nickname", sentence: "His sobriquet, 'the Wizard,' came from his card tricks." },
  { word: "solicitous",   def: "showing caring concern", sentence: "The solicitous nurse checked on him every hour." },
  { word: "soporific",    def: "tending to cause sleep", sentence: "His soporific lectures put even the front row to sleep." },
  { word: "specious",     def: "seeming true but actually false", sentence: "The salesman's specious arguments fooled no one." },
  { word: "sporadic",     def: "happening at irregular intervals", sentence: "Her sporadic attendance hurt her grade." },
  { word: "spurious",     def: "fake; not what it claims to be", sentence: "The painting turned out to be a spurious copy." },
  { word: "squander",     def: "to waste in a careless way", sentence: "Don't squander your savings on impulse buys." },
  { word: "staid",        def: "serious and not changing", sentence: "The staid old bank refused to update its website." },
  { word: "stoic",        def: "showing no emotion under stress", sentence: "She was stoic through the long, painful recovery." },
  { word: "stolid",       def: "calm, dependable, and unemotional", sentence: "His stolid expression never changed, even during good news." },
  { word: "strident",     def: "loud and harsh in sound or tone", sentence: "Their strident demands drowned out the quieter voices." },
  { word: "stymie",       def: "to prevent from making progress", sentence: "Heavy rain stymied our plans for the picnic." },
  { word: "succinct",     def: "expressed clearly in few words", sentence: "Please give a succinct summary of the meeting." },
  { word: "supercilious", def: "behaving as if you feel superior", sentence: "His supercilious tone made everyone want to leave." },
  { word: "superfluous",  def: "more than is needed", sentence: "Cut any superfluous adjectives from your draft." },
  { word: "surfeit",      def: "an excess; too much", sentence: "After the holidays, we had a surfeit of leftovers." },
  { word: "surreptitious",def: "done in a quiet, secret way", sentence: "She took a surreptitious photo of the artwork." },
  { word: "sycophant",    def: "a person who flatters to gain favor", sentence: "The CEO surrounded himself with sycophants and no honest critics." },
  { word: "taciturn",     def: "saying little; reserved", sentence: "Our taciturn neighbor rarely says hello." },
  { word: "tantamount",   def: "essentially the same as", sentence: "Silence in this case is tantamount to consent." },
  { word: "tedious",      def: "boringly long or slow", sentence: "Sorting old papers was tedious but necessary work." },
  { word: "temerity",     def: "rude boldness; nerve", sentence: "He had the temerity to interrupt the senator mid-sentence." },
  { word: "tenacious",    def: "holding on tightly; not giving up", sentence: "Her tenacious work ethic earned her the promotion." },
  { word: "tenuous",      def: "weak and easily broken", sentence: "The connection between the two events is tenuous at best." },
  { word: "terse",        def: "brief and to the point, sometimes rudely", sentence: "His terse reply left no room for follow-up questions." },
  { word: "timorous",     def: "shy and afraid", sentence: "The timorous kitten hid under the couch for hours." },
  { word: "torpid",       def: "sluggish and inactive", sentence: "After the huge meal, we were all torpid on the porch." },
  { word: "tortuous",     def: "full of twists and turns", sentence: "The tortuous mountain road tested every driver's nerves." },
  { word: "tractable",    def: "easily managed or controlled", sentence: "The new puppy was surprisingly tractable in training class." },
  { word: "transient",    def: "lasting only a short time", sentence: "Fame can be transient, fortune even more so." },
  { word: "trepidation",  def: "a feeling of fear about what's coming", sentence: "She walked onstage with visible trepidation." },
  { word: "truculent",    def: "eager to argue or fight", sentence: "The truculent kid started a fight at recess." },
  { word: "turpitude",    def: "wicked or shameful behavior", sentence: "He was disbarred for moral turpitude." },
  { word: "ubiquitous",   def: "seeming to be everywhere at once", sentence: "Smartphones are ubiquitous, even in remote villages." },
  { word: "umbrage",      def: "offense or annoyance", sentence: "She took umbrage at his criticism of her cooking." },
  { word: "unctuous",     def: "overly smooth and fake-friendly", sentence: "The unctuous salesman complimented every customer's outfit." },
  { word: "undulate",     def: "to move in a smooth wave-like motion", sentence: "The fields of wheat undulate in the summer breeze." },
  { word: "unequivocal",  def: "leaving no doubt at all", sentence: "The doctor's diagnosis was unequivocal." },
  { word: "untenable",    def: "impossible to defend or maintain", sentence: "His position became untenable after the new evidence emerged." },
  { word: "upbraid",      def: "to find fault and scold", sentence: "The coach upbraided the team for sloppy practice." },
  { word: "urbane",       def: "smooth, polished, and worldly", sentence: "Their urbane host kept the dinner conversation lively." },
  { word: "usurp",        def: "to take power or position by force", sentence: "The general tried to usurp the throne while the king was away." },
  { word: "vacillate",    def: "to keep switching between options", sentence: "She vacillated between law school and art school for months." },
  { word: "vacuous",      def: "empty of thought or meaning", sentence: "His vacuous reply showed he hadn't read the brief." },
  { word: "vapid",        def: "dull and lacking spirit", sentence: "The party was full of vapid small talk." },
  { word: "venerable",    def: "respected because of age or wisdom", sentence: "We visited the venerable cathedral on our trip." },
  { word: "veracity",     def: "truthfulness; accuracy", sentence: "The court will determine the veracity of the witness's statement." },
  { word: "verbose",      def: "using more words than needed", sentence: "His verbose emails buried the actual question." },
  { word: "vex",          def: "to annoy or worry someone", sentence: "Slow internet vexes me more than any other annoyance." },
  { word: "vicarious",    def: "experienced through someone else", sentence: "He gets vicarious thrills from watching extreme sports." },
  { word: "vicissitude",  def: "a change in fortune, usually unwelcome", sentence: "She endured many vicissitudes before becoming successful." },
  { word: "vilify",       def: "to speak about with strong contempt", sentence: "Critics vilified the singer for her political stance." },
  { word: "vindicate",    def: "to clear someone of blame; to prove right", sentence: "Years later, her predictions vindicated her early concerns." },
  { word: "vindictive",   def: "having a strong desire for revenge", sentence: "His vindictive response made the rivalry far worse." },
  { word: "virtuoso",     def: "a person with exceptional skill", sentence: "The young pianist is already a virtuoso at sixteen." },
  { word: "vitriolic",    def: "filled with bitter criticism", sentence: "The vitriolic review hurt the chef's reputation." },
  { word: "vituperative", def: "containing harsh, abusive language", sentence: "Her vituperative speech shocked even her supporters." },
  { word: "vivacious",    def: "lively and full of spirit", sentence: "Their vivacious host kept everyone laughing all night." },
  { word: "vociferous",   def: "loud and forceful in speech", sentence: "Vociferous protests led the council to reverse its decision." },
  { word: "voracious",    def: "having a huge appetite, for food or for anything", sentence: "Our voracious reader finishes a novel a week." },
  { word: "wanton",       def: "deliberately and senselessly harmful", sentence: "The wanton destruction shocked the entire neighborhood." },
  { word: "wary",         def: "cautious about possible danger", sentence: "Be wary of emails asking for your password." },
  { word: "winsome",      def: "charming in an innocent way", sentence: "His winsome smile made everyone want to help." },
  { word: "wistful",      def: "softly sad about something past or wished for", sentence: "She had a wistful look while flipping through old photos." },
  { word: "wizened",      def: "shrunken and wrinkled with age", sentence: "The wizened apple had shrunk to half its size." },
  { word: "zealous",      def: "showing great passion in pursuit of a cause", sentence: "She is zealous about recycling everything that can be reused." },
  { word: "zenith",       def: "the highest point of something", sentence: "Reaching the team captain role marked the zenith of her career." },
];

if (typeof module !== "undefined") module.exports = { STARTER_WORDS };
